### 1. 📥​ Imports

In [12]:
import sys, os
from pathlib import Path
import pandas as pd

SRC = Path.cwd().parent / "src"
sys.path.insert(0, str(SRC))

from tcibench.preparation import (Dataset, DatasetMetadata, load_dataset, load_metadata)

from tcibench.generation.llms import (
    LLMClient, LLMConfig,
    load_sampling_plan, load_schema,
    run_generation,
    get_context, build_generation_messages
)

### 2. ⚙️​ Configs

In [13]:
PROJECT_ROOT = next(
    (path for path in (Path.cwd(), *Path.cwd().parents)
     if (path / "src" / "tcibench" / "preparation" / "metadata.json").is_file()),
    None,
)

In [14]:
# Reproducibility
SPLIT_SEED = 42
SAMPLING_SEED = 42
GENERATION_SEED = 42

# Generation protocol
EXAMPLES_PER_CLASS = 10
RECORDS_PER_BATCH = 10

📂​ Datasets

In [ ]:
DATASETS = {
    "diabetes": "Diabetes",
    "sick": "Thyroid Sick",
    "predictive_maintenance": "Predictive Maintenance",
    "adult": "Adult Income"
}

RAW_ROOT = PROJECT_ROOT / "data" / "raw"
PROCESSED_ROOT = PROJECT_ROOT / "data" / "processed" / f"split_seed_{SPLIT_SEED}"

RAW_PATHS = {
    "diabetes": RAW_ROOT / "diabetes.csv",
    "sick": RAW_ROOT / "sick.arff",
    "predictive_maintenance": RAW_ROOT / "predictive_maintenance.csv",
    "adult": RAW_ROOT / "adult.csv"
}

🤖 LLMs

In [16]:
# API keys
NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")

# LLMs
MODELS = {
    "deepseek_v4_flash": LLMConfig(
        model="deepseek-ai/deepseek-v4-flash-0731",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=NVIDIA_API_KEY,
        max_tokens=16384,
        temperature=0.7,
        generation_kwargs={
            "top_p": 0.95,
            "extra_body": {
                "chat_template_kwargs": {
                    "thinking": False,
                    "reasoning_effort": "high",
                }
            },
        },
    ),

    "phi_4_mini_instruct": LLMConfig(
        model="phi-4-mini-instruct",
        base_url="http://192.168.68.124:1234/v1",
        api_key="lm-studio",
        max_tokens=4096,
        temperature=0.7,
    ),

    "deepseek_r1_distill_llama_8b": LLMConfig(
        model="deepseek-r1-distill-llama-8b",
        base_url="http://192.168.68.124:1234/v1",
        api_key="lm-studio",
        max_tokens=4096,
        temperature=0.7,
    ),

    "qwen3_4b": LLMConfig(
        model="qwen3-4b",
        base_url="http://192.168.68.124:1234/v1",
        api_key="lm-studio",
        max_tokens=4096,
        temperature=0.7,
    ),

    "meta_llama_3_1_8b_instruct": LLMConfig(
        model="meta-llama-3.1-8b-instruct",
        base_url="http://192.168.68.124:1234/v1",
        api_key="lm-studio",
        max_tokens=4096,
        temperature=0.7,
    ),

    "qwen3_1_7b": LLMConfig(
        model="qwen3-1.7b:3",
        base_url="http://192.168.68.124:1234/v1",
        api_key="lm-studio",
        max_tokens=4096,
        temperature=0.7,
    ),

    "kimi_k3": LLMConfig(
        model="moonshotai/kimi-k3",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=NVIDIA_API_KEY,
        max_tokens=16384,
        temperature=1.0,
        generation_kwargs={
            "reasoning_effort": "max",
        },
    ),
    "glm_5_3": LLMConfig(
        model="z-ai/glm-5.3",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=NVIDIA_API_KEY,
        max_tokens=4096,
        temperature=1.0,
        generation_kwargs={
            "stream": False,
            "reasoning_effort": "low",
        },
    ),
    "gemma_4_31b": LLMConfig(
        model="google/gemma-4-31b-it",
        base_url="https://integrate.api.nvidia.com/v1",
        api_key=NVIDIA_API_KEY,
        max_tokens=4096,
        temperature=1.0,
        generation_kwargs={
            "extra_body": {
                "chat_template_kwargs": {
                    "enable_thinking": False,
                },
            },
            "stream": False,
        },
        ),
}

### 3. 📂​ Dataset

In [17]:
def inspect_dataset(
    data: pd.DataFrame,
    metadata: DatasetMetadata,
    cleaned: pd.DataFrame,
    cleaning_stats: dict,
):
    """Inspect a dataset before running the experiment."""

    print(f"Dataset: {metadata.display_name}")
    print(f"Target: {metadata.target_column}")

    print("\nRaw data")
    print(f"Shape: {data.shape}")
    display(data.head())

    print("\nCleaning")
    print(f"Shape after cleaning: {cleaned.shape}")
    print(f"Removed columns: {cleaning_stats['dropped_columns']}")
    print(f"Removed rows with missing values: {cleaning_stats['removed_missing_rows']}")
    print(f"Removed duplicate rows: {cleaning_stats['removed_duplicate_rows']}")

    print("\nCleaned data")
    display(cleaned.head())

    print("\nTarget distribution")
    target = metadata.target_column
    display(pd.DataFrame({
        "count": cleaned[target].value_counts(),
        "proportion": cleaned[target].value_counts(normalize=True).mul(100).round(2),
    }))

    target_counts = cleaned[target].value_counts()
    print(f"Imbalance ratio: {target_counts.max() / target_counts.min():.2f}")

In [ ]:
DATASET_ID = "adult"

metadata = load_metadata(DATASET_ID)
data = load_dataset(RAW_PATHS[DATASET_ID])

dataset = Dataset(data, metadata)

cleaned, cleaning_report = dataset.preprocessing.clean(data)
folds = dataset.preprocessing.split(cleaned)

inspect_dataset(data, metadata, cleaned, cleaning_report)

train, test, audit = folds[0]

counts = train[metadata.target_column].value_counts()
majority_class = counts.idxmax()
minority_class = counts.idxmin()

majority_count = int(counts[majority_class])
minority_count = int(counts[minority_class])
records_to_generate = majority_count - minority_count
imbalance_ratio = majority_count / minority_count

print(f"Dataset: {metadata.display_name}")
print(f"Cleaned: {cleaned.shape}")
print(f"Fold 1 — Train: {train.shape} | Test: {test.shape}")
print(f"Majority: {majority_class} ({majority_count})")
print(f"Minority: {minority_class} ({minority_count})")
print(f"Imbalance ratio: {imbalance_ratio:.2f}")
print(f"Records to generate: {records_to_generate}")

Dataset: AI4I 2020 Predictive Maintenance
Target: Target

Raw data
Shape: (10000, 10)

,UDI,Product ID,Type,Air temperature (K),Process temperature (K),Rotational speed (rpm),Torque (Nm),Tool wear (min),Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure

Cleaning
Shape after cleaning: (10000, 7)
Removed columns: ['UDI', 'Product ID', 'Failure Type']
Removed rows with missing values: 0
Removed duplicate rows: 0

Cleaned data

,Type,Air temperature (K),Process temperature (K),Rotational speed (rpm),Torque (Nm),Tool wear (min),Target
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0

Target distribution

        count  proportion
Target
0        9661       96.61
1         339        3.39

Imbalance ratio: 28.50
Dataset: AI4I 2020 Predictive Maintenance
Cleaned: (10000, 7)
Fold 1 — Train: (8000, 7) | Test: (2000, 7)
Majority: 0 (7728)
Minority: 1 (272)
Imbalance ratio: 28.41
Records to generate: 7456

In [19]:
ARTIFACTS_ROOT = PROJECT_ROOT / "artifacts"

sampling_plans = []
schemas = []

for fold_id, (train, test, audit) in enumerate(folds):
    counts = train[metadata.target_column].value_counts()
    majority_class = counts.idxmax()
    minority_class = counts.idxmin()

    records_to_generate = int(counts[majority_class] - counts[minority_class])

    sampling_plan = load_sampling_plan(
        train,
        metadata,
        records_to_generate=records_to_generate,
        records_per_batch=RECORDS_PER_BATCH,
        examples_per_class=EXAMPLES_PER_CLASS,
        fold_id=fold_id,
        sampling_seed=SAMPLING_SEED,
        output_root=ARTIFACTS_ROOT / "generation" / "sampling",
    )

    schema = load_schema(
        train,
        metadata,
        minority_class=minority_class,
        fold_id=fold_id,
        records_per_batch=RECORDS_PER_BATCH,
        output_root=ARTIFACTS_ROOT / "generation" / "schemas",
    )

    sampling_plans.append(sampling_plan)
    schemas.append(schema)

### 4. 📄​ Prompt example

In [20]:
# Prompt example from fold 0
fold_id = 0

train, test, audit = folds[fold_id]
sampling_plan = sampling_plans[fold_id]

counts = train[metadata.target_column].value_counts()
minority_class = counts.idxmin()

context = get_context(
    train,
    sampling_plan,
    dataset_id=metadata.dataset_id,
    call_index=0,
)

messages = build_generation_messages(
    context,
    metadata,
    minority_class=minority_class,
    records_per_batch=RECORDS_PER_BATCH,
    examples_per_class=EXAMPLES_PER_CLASS,
)

for message in messages:
    print(f"\n--- {message['role'].upper()} ---\n")
    print(message["content"])

--- SYSTEM ---

You are a tabular synthetic data generator.

Given the dataset context provided, generate new synthetic
samples that are plausible within the dataset domain.

Use the dataset description, column descriptions, and reference examples
to understand the meaning of the attributes and the relationships among them.

Each attribute value must be plsausible on its own and consistent with the others.
Preserve realistic relationships, dependencies, and correlations among
attributes within the context of the dataset domain.

Do not copy, reproduce, or minimally modify any reference record.
Generate genuinely new combinations of attribute values.

--- USER ---

Dataset description:
Synthetic dataset modelled on industrial predictive maintenance: sensor measurements for predicting machine failures.

Target column:
Target

Column descriptions:
Type: Product quality variant: L (low), M (medium) or H (high).
Air temperature (K): Air temperature in kelvin.
Process temperature (K): Process temperature in kelvin.
Rotational speed (rpm): Rotational speed in revolutions per minute.
Torque (Nm): Torque in newton-metres.
Tool wear (min): Tool wear in minutes.
Target: Machine failure (0: no failure; 1: failure).

Reference examples from the dataset, grouped by class
(10 examples per class):
CLASS 0
[
 {"Target":0,"Type":"L","Air temperature (K)":300.5,"Process temperature (K)":309.7,"Rotational speed (rpm)":1841,"Torque (Nm)":24.6,"Tool wear (min)":143},
 {"Target":0,"Type":"H","Air temperature (K)":300.8,"Process temperature (K)":311.1,"Rotational speed (rpm)":1698,"Torque (Nm)":24.8,"Tool wear (min)":156},
 {"Target":0,"Type":"L","Air temperature (K)":299.8,"Process temperature (K)":310.3,"Rotational speed (rpm)":1687,"Torque (Nm)":30.4,"Tool wear (min)":33},
 {"Target":0,"Type":"L","Air temperature (K)":300.4,"Process temperature (K)":311.7,"Rotational speed (rpm)":1444,"Torque (Nm)":51.2,"Tool wear (min)":174},
 {"Target":0,"Type":"M","Air temperature (K)":297.4,"Process temperature (K)":308.6,"Rotational speed (rpm)":1434,"Torque (Nm)":44.4,"Tool wear (min)":193},
 {"Target":0,"Type":"M","Air temperature (K)":301.9,"Process temperature (K)":310.9,"Rotational speed (rpm)":1483,"Torque (Nm)":37.0,"Tool wear (min)":35},
 {"Target":0,"Type":"L","Air temperature (K)":297.9,"Process temperature (K)":307.8,"Rotational speed (rpm)":1451,"Torque (Nm)":38.2,"Tool wear (min)":80},
 {"Target":0,"Type":"L","Air temperature (K)":301.1,"Process temperature (K)":311.0,"Rotational speed (rpm)":1378,"Torque (Nm)":51.1,"Tool wear (min)":190},
 {"Target":0,"Type":"L","Air temperature (K)":301.4,"Process temperature (K)":311.1,"Rotational speed (rpm)":1952,"Torque (Nm)":22.7,"Tool wear (min)":131},
 {"Target":0,"Type":"M","Air temperature (K)":304.4,"Process temperature (K)":313.6,"Rotational speed (rpm)":1510,"Torque (Nm)":38.9,"Tool wear (min)":199}
]

CLASS 1
[
 {"Target":1,"Type":"L","Air temperature (K)":302.0,"Process temperature (K)":311.2,"Rotational speed (rpm)":1270,"Torque (Nm)":65.3,"Tool wear (min)":182},
 {"Target":1,"Type":"M","Air temperature (K)":300.6,"Process temperature (K)":309.4,"Rotational speed (rpm)":1367,"Torque (Nm)":63.2,"Tool wear (min)":45},
 {"Target":1,"Type":"M","Air temperature (K)":302.0,"Process temperature (K)":310.4,"Rotational speed (rpm)":1212,"Torque (Nm)":55.6,"Tool wear (min)":79},
 {"Target":1,"Type":"L","Air temperature (K)":302.5,"Process temperature (K)":310.2,"Rotational speed (rpm)":1307,"Torque (Nm)":54.0,"Tool wear (min)":86},
 {"Target":1,"Type":"L","Air temperature (K)":302.6,"Process temperature (K)":311.0,"Rotational speed (rpm)":1284,"Torque (Nm)":68.0,"Tool wear (min)":114},
 {"Target":1,"Type":"M","Air temperature (K)":296.7,"Process temperature (K)":307.8,"Rotational speed (rpm)":1258,"Torque (Nm)":69.0,"Tool wear (min)":105},
 {"Target":1,"Type":"L","Air temperature (K)":301.7,"Process temperature (K)":310.2,"Rotational speed (rpm)":1311,"Torque (Nm)":57.4,"Tool wear (min)":40},
 {"Target":1,"Type":"M","Air temperature (K)":301.8,"Process temperature (K)":310.1,"Rotational speed (rpm)":2372,"Torque (Nm)":13.9,"Tool wear (min)":205},
 {"Target":1,"Type":"L","Air temperature (K)":303.0,"Process temperature (K)":311.3,"Rotational speed (rpm)":1365,"Torque (Nm)":56.2,"Tool wear (min)":146},
 {"Target":1,"Type":"L","Air temperature (K)":299.3,"Process temperature (K)":308.6,"Rotational speed (rpm)":1384,"Torque (Nm)":53.6,"Tool wear (min)":218}
]

Generation task:
Generate exactly 10 new synthetic records belonging to
the target class Target=1, with attribute combinations
that are plausible for this class.

### 5. 🤖 LLMs generation

In [21]:
RUN_MODELS = [
    "gemma_4_31b",
]

In [22]:
for fold_id, (train, test, audit) in enumerate(folds):
    schema = schemas[fold_id]
    sampling_plan = sampling_plans[fold_id]

    for model_name in RUN_MODELS:
        config = MODELS[model_name]
        client = LLMClient(config)

        result = run_generation(
            train,
            metadata,
            schema,
            sampling_plan,
            client,
            test=test,
            fold_id=fold_id,
            generation_seed=GENERATION_SEED,
            max_concurrent_calls=8,
            output_root=PROJECT_ROOT / "artifacts" / "generation",
        )

        print(result.summary)

Dataset: predictive_maintenance | Model: google/gemma-4-31b-it | Fold: 0 | Minority class: 1 | Target records: 7456 | Planned contexts: 746

Context 1/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 10/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 675

Context 2/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 20/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 687

Context 3/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 30/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 804

Context 4/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 40/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 675

Context 5/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 50/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1660 | Output tokens: 803

Context 6/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 60/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 807

Context 7/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 70/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 806

Context 8/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 80/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1658 | Output tokens: 804

Context 9/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 90/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 10/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 100/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 674

Context 11/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 110/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 821

Context 12/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 120/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 13/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 130/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 803

Context 14/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 140/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 805

Context 15/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 150/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 677

Context 16/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 160/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 803

Context 17/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 170/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 805

Context 18/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 180/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 804

Context 19/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 190/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 804

Context 20/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 200/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 806

Context 21/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 210/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 804

Context 22/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 220/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 685

Context 23/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 230/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1666 | Output tokens: 806

Context 24/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 240/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1660 | Output tokens: 804

Context 25/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 250/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 675

Context 26/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 260/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 677

Context 27/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 270/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 805

Context 28/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 280/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1660 | Output tokens: 801

Context 29/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 290/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 805

Context 30/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 300/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 804

Context 31/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 310/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 803

Context 32/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 320/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 803

Context 33/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 330/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 675

Context 34/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 340/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1659 | Output tokens: 804

Context 35/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 350/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 804

Context 36/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 360/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 674

Context 37/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 370/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1667 | Output tokens: 804

Context 38/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 380/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 820

Context 39/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 390/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 803

Context 40/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 400/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1667 | Output tokens: 807

Context 41/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 410/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 805

Context 42/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 420/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 43/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 430/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 677

Context 44/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 440/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 807

Context 45/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 450/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 804

Context 46/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 460/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 677

Context 47/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 470/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 48/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 480/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1666 | Output tokens: 675

Context 49/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 490/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 806

Context 50/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 500/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 51/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 510/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 677

Context 52/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 520/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 806

Context 53/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 530/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 804

Context 54/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 540/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 807

Context 55/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 550/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 805

Context 56/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 560/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 805

Context 57/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 570/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1660 | Output tokens: 806

Context 58/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 580/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 59/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 590/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 805

Context 60/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 600/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1664 | Output tokens: 676

Context 61/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 610/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1659 | Output tokens: 805

Context 62/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 620/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1663 | Output tokens: 805

Context 63/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 630/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1660 | Output tokens: 807

Context 64/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 640/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1657 | Output tokens: 674

Context 65/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 650/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 804

Context 66/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 660/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1660 | Output tokens: 803

Context 67/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 670/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1661 | Output tokens: 821

Context 68/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 680/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1662 | Output tokens: 804

Context 69/746 | Attempt 1 | Returned: 10 | Valid: 10 | Accepted: 10 | Block: 10/10 | Total: 690/7456
Requested class: Target=1
Returned valid groups: {1: 10}
Discarded -> Format/schema: 0 | Duplicate: 0 | Copied prompt: 0 | Copied train/test: 0
Input tokens: 1665 | Output tokens: 806
